# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

#on:
#  push:
#  tags:
#    -v*
on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Lockdown CI Security
        uses: InstaCode/lockdown@v1
        with:
          users: jason-edstrom, dependabot-preview
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create settings file
        uses: s4u/maven-settings-action@v2.1.0
        with:
          sonatypeSnapshots: true
          #servers: '[{"id": "github", "username": "jason-edstrom", "password": "${{secrets.PACKAGES_PAT}}"}]'
          #override: true
          #githubServer: false
        env:
          GITHUB_ACTOR: $GITHUB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
            # Artifact name
            name: Settings
            # A file, directory or wildcard pattern that describes what to upload
            path: ~/.m2/settings.xml
      - name: Run package
        run: mvn -Pgithub package deploy -B -e -f pom.xml -DskipTests
